[2017-03-05 09:31:10] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /"" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:143)"} []
[2017-03-05 15:56:37] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /api/user"" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /api/user\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:143)"} []
[2017-03-05 15:56:38] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"ec8bc8","_route":"_wdt"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/_wdt/ec8bc8","method":"GET"} []
[2017-03-05 15:56:49] request.INFO: Matched route "api_user". {"route":"api_user","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::userAction","_route":"api_user"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/api/user","method":"GET"} []
[2017-03-05 15:56:49] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-05 15:56:49] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 15:56:49] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-03-05 15:56:49] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2017-03-05 15:56:49] security.DEBUG: Calling Authentication entry point. [] []
[2017-03-05 15:56:49] request.INFO: Matched route "api_user". {"route":"api_user","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::userAction","_route":"api_user"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/api/user?ticket=ST-207976-T9eDEUUp45L5WBx7i33g-cas.u-pem.fr","method":"GET"} []
[2017-03-05 15:56:49] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-05 15:56:49] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 15:56:49] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"main","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 15:56:49] security.INFO: Guard authentication successful! {"token":"[object] (Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken: PostAuthenticationGuardToken(user=\"vrasquie\", authenticated=true, roles=\"ROLE_USER\"))","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 15:56:49] security.DEBUG: Guard authenticator set success response. {"response":"[object] (Symfony\\Component\\HttpFoundation\\RedirectResponse: HTTP/1.0 302 Found\r\nCache-Control: no-cache, private\r\nLocation:      https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/api/user\r\n\r\n<!DOCTYPE html>\n<html>\n    <head>\n        <meta charset=\"UTF-8\" />\n        <meta http-equiv=\"refresh\" content=\"1;url=https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/api/user\" />\n\n        <title>Redirecting to https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/api/user</title>\n    </head>\n    <body>\n        Redirecting to <a href=\"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/api/user\">https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/api/user</a>.\n    </body>\n</html>)","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 15:56:49] security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 15:56:49] security.DEBUG: The "PRayno\CasAuthBundle\Security\CasAuthenticator" authenticator set the response. Any later authenticator will not be called {"authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 15:56:49] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-05 15:56:49] request.INFO: Matched route "api_user". {"route":"api_user","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::userAction","_route":"api_user"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/api/user","method":"GET"} []
[2017-03-05 15:56:49] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-05 15:56:49] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-05 15:56:49] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-05 15:56:49] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 15:56:49] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.lastname AS lastname_3, t0.uid AS uid_4, t0.email AS email_5, t0.etu_id AS etu_id_6, t0.class AS class_7, t0.status AS status_8 FROM user_app t0 WHERE t0.uid = ? LIMIT 1 ["vrasquie"] []
[2017-03-05 15:56:49] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-05 16:02:23] request.INFO: Matched route "api_user". {"route":"api_user","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::userAction","_route":"api_user"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/api/user","method":"GET"} []
[2017-03-05 16:02:23] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-05 16:02:23] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-05 16:02:23] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-05 16:02:23] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 16:02:23] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.lastname AS lastname_3, t0.uid AS uid_4, t0.email AS email_5, t0.etu_id AS etu_id_6, t0.class AS class_7, t0.status AS status_8 FROM user_app t0 WHERE t0.uid = ? LIMIT 1 ["vrasquie"] []
[2017-03-05 16:03:34] request.INFO: Matched route "api_user". {"route":"api_user","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::userAction","_route":"api_user"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/api/user","method":"GET"} []
[2017-03-05 16:03:34] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-05 16:03:34] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-05 16:03:34] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-05 16:03:34] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 16:03:34] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.lastname AS lastname_3, t0.uid AS uid_4, t0.email AS email_5, t0.etu_id AS etu_id_6, t0.class AS class_7, t0.status AS status_8 FROM user_app t0 WHERE t0.uid = ? LIMIT 1 ["vrasquie"] []
[2017-03-05 16:03:34] doctrine.DEBUG: SELECT NEXTVAL('user_app_id_seq') [] []
[2017-03-05 16:03:34] doctrine.DEBUG: "START TRANSACTION" [] []
[2017-03-05 16:03:34] doctrine.DEBUG: INSERT INTO user_app (id, name, lastname, uid, email, etu_id, class, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?) {"1":6,"2":"VINCENT","3":"RASQUIER","4":"vrasquie","5":"vrasquie@etud.u-pem.fr","6":161224,"7":"Esipe/Informatique et RÃ©seaux 1","8":true} []
[2017-03-05 16:03:34] doctrine.DEBUG: "COMMIT" [] []
[2017-03-05 16:03:34] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-05 16:04:22] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /~vrasquie/cas/api/info"" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/dev/classes.php line 3485 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /~vrasquie/cas/api/info\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/dev/classes.php:3485, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:143)"} []
[2017-03-05 16:04:24] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"76a0ef","_route":"_wdt"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/_wdt/76a0ef","method":"GET"} []
[2017-03-05 16:04:30] request.INFO: Matched route "api_service". {"route":"api_service","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::serviceAction","_route":"api_service"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/api/service","method":"GET"} []
[2017-03-05 16:04:30] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-05 16:04:30] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-05 16:04:30] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-05 16:04:30] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 16:04:30] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-05 19:51:39] php.CRITICAL: Fatal Compile Error: Access level to AppBundle\Controller\ApiController::getUser() must be protected (as in class Symfony\Bundle\FrameworkBundle\Controller\Controller) or weaker {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: Access level to AppBundle\\Controller\\ApiController::getUser() must be protected (as in class Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller) or weaker at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Controller/ApiController.php:10)"} []
[2017-03-05 19:51:39] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: Access level to AppBundle\Controller\ApiController::getUser() must be protected (as in class Symfony\Bundle\FrameworkBundle\Controller\Controller) or weaker" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Controller/ApiController.php line 10 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: Access level to AppBundle\\Controller\\ApiController::getUser() must be protected (as in class Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller) or weaker at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Controller/ApiController.php:10)"} []
[2017-03-05 19:52:47] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /flush"" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /flush\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:143)"} []
[2017-03-05 19:52:48] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"e556b5","_route":"_wdt"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/_wdt/e556b5","method":"GET"} []
[2017-03-05 19:53:22] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/dev/classes.php line 3485 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/dev/classes.php:3485, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:143)"} []
[2017-03-05 19:53:24] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"05b9c5","_route":"_wdt"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/_wdt/05b9c5","method":"GET"} []
[2017-03-05 19:53:33] request.INFO: Matched route "flush". {"route":"flush","route_parameters":{"_controller":"AppBundle\\Controller\\MainController::flushAction","_route":"flush"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/flush","method":"GET"} []
[2017-03-05 19:53:33] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-05 19:53:33] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 19:53:33] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-03-05 19:53:33] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2017-03-05 19:53:33] security.DEBUG: Calling Authentication entry point. [] []
[2017-03-05 19:53:33] request.INFO: Matched route "flush". {"route":"flush","route_parameters":{"_controller":"AppBundle\\Controller\\MainController::flushAction","_route":"flush"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/flush?ticket=ST-210129-BgecC0JQQswoFqJ9tNrO-cas.u-pem.fr","method":"GET"} []
[2017-03-05 19:53:33] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-05 19:53:33] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 19:53:33] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"main","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 19:53:33] security.INFO: Guard authentication successful! {"token":"[object] (Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken: PostAuthenticationGuardToken(user=\"vrasquie\", authenticated=true, roles=\"ROLE_USER\"))","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 19:53:33] security.DEBUG: Guard authenticator set success response. {"response":"[object] (Symfony\\Component\\HttpFoundation\\RedirectResponse: HTTP/1.0 302 Found\r\nCache-Control: no-cache, private\r\nLocation:      https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/flush\r\n\r\n<!DOCTYPE html>\n<html>\n    <head>\n        <meta charset=\"UTF-8\" />\n        <meta http-equiv=\"refresh\" content=\"1;url=https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/flush\" />\n\n        <title>Redirecting to https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/flush</title>\n    </head>\n    <body>\n        Redirecting to <a href=\"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/flush\">https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/flush</a>.\n    </body>\n</html>)","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 19:53:33] security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 19:53:33] security.DEBUG: The "PRayno\CasAuthBundle\Security\CasAuthenticator" authenticator set the response. Any later authenticator will not be called {"authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 19:53:33] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-05 19:53:33] request.INFO: Matched route "flush". {"route":"flush","route_parameters":{"_controller":"AppBundle\\Controller\\MainController::flushAction","_route":"flush"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/flush","method":"GET"} []
[2017-03-05 19:53:33] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-05 19:53:33] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-05 19:53:33] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-05 19:53:33] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 19:53:33] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-05 19:54:08] request.INFO: Matched route "api_user". {"route":"api_user","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::userAction","_route":"api_user"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/api/user","method":"GET"} []
[2017-03-05 19:54:08] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-05 19:54:08] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-05 19:54:08] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-05 19:54:08] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 19:54:08] doctrine.DEBUG: SELECT t0.id AS id_1, t0.uid AS uid_2 FROM user_app t0 WHERE t0.uid = ? LIMIT 1 ["vrasquie"] []
[2017-03-05 19:54:08] php.CRITICAL: Fatal Error: Call to undefined method AppBundle\Controller\ApiController::sendSuccess() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to undefined method AppBundle\\Controller\\ApiController::sendSuccess() at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Controller/ApiController.php:85)"} []
[2017-03-05 19:54:08] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "sendSuccess" of class "AppBundle\Controller\ApiController"." at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Controller/ApiController.php line 85 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"sendSuccess\" of class \"AppBundle\\Controller\\ApiController\". at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Controller/ApiController.php:85)"} []
[2017-03-05 19:54:08] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-05 19:54:09] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"37218b","_route":"_wdt"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/_wdt/37218b","method":"GET"} []
[2017-03-05 19:54:51] request.INFO: Matched route "api_user". {"route":"api_user","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::userAction","_route":"api_user"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/api/user","method":"GET"} []
[2017-03-05 19:54:51] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-05 19:54:51] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-05 19:54:51] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-05 19:54:51] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 19:54:51] doctrine.DEBUG: SELECT t0.id AS id_1, t0.uid AS uid_2 FROM user_app t0 WHERE t0.uid = ? LIMIT 1 ["vrasquie"] []
[2017-03-05 19:54:51] php.CRITICAL: Fatal Error: Call to private method AppBundle\Service\ResponseService::sendSuccess() from context 'AppBundle\Controller\ApiController' {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to private method AppBundle\\Service\\ResponseService::sendSuccess() from context 'AppBundle\\Controller\\ApiController' at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Controller/ApiController.php:86)"} []
[2017-03-05 19:54:51] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to private method AppBundle\Service\ResponseService::sendSuccess() from context 'AppBundle\Controller\ApiController'" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Controller/ApiController.php line 86 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to private method AppBundle\\Service\\ResponseService::sendSuccess() from context 'AppBundle\\Controller\\ApiController' at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/src/AppBundle/Controller/ApiController.php:86)"} []
[2017-03-05 19:54:52] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-05 19:54:52] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"b7c6f6","_route":"_wdt"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/_wdt/b7c6f6","method":"GET"} []
[2017-03-05 19:55:38] request.INFO: Matched route "api_user". {"route":"api_user","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::userAction","_route":"api_user"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/api/user","method":"GET"} []
[2017-03-05 19:55:38] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-05 19:55:38] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-05 19:55:38] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-05 19:55:38] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 19:55:38] doctrine.DEBUG: SELECT t0.id AS id_1, t0.uid AS uid_2 FROM user_app t0 WHERE t0.uid = ? LIMIT 1 ["vrasquie"] []
[2017-03-05 19:55:38] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-05 19:55:46] request.INFO: Matched route "api_service". {"route":"api_service","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::serviceAction","_route":"api_service"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/api/service","method":"GET"} []
[2017-03-05 19:55:46] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-05 19:55:46] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-05 19:55:46] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-05 19:55:46] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 19:55:46] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-05 19:55:53] request.INFO: Matched route "flush". {"route":"flush","route_parameters":{"_controller":"AppBundle\\Controller\\MainController::flushAction","_route":"flush"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/flush","method":"GET"} []
[2017-03-05 19:55:53] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-05 19:55:53] security.DEBUG: User was reloaded from a user provider. {"username":"vrasquie","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-05 19:55:53] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-05 19:55:53] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-05 19:55:54] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-06 00:47:49] request.INFO: Matched route "api_user". {"route":"api_user","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::userAction","_route":"api_user"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/api/user","method":"POST"} []
[2017-03-06 00:47:49] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-06 00:47:49] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-06 00:47:49] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-03-06 00:47:49] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2017-03-06 00:47:49] security.DEBUG: Calling Authentication entry point. [] []
[2017-03-06 04:57:49] request.INFO: Matched route "flush". {"route":"flush","route_parameters":{"_controller":"AppBundle\\Controller\\MainController::flushAction","_route":"flush"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/flush","method":"POST"} []
[2017-03-06 04:57:49] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-06 04:57:49] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"PRayno\\CasAuthBundle\\Security\\CasAuthenticator"} []
[2017-03-06 04:57:49] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-03-06 04:57:49] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2017-03-06 04:57:49] security.DEBUG: Calling Authentication entry point. [] []
[2017-03-10 16:13:14] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:138)"} []
[2017-03-10 16:13:14] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php line 31) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php:31)"} []
[2017-03-10 16:13:14] php.CRITICAL: Uncaught Notice: Undefined index: server_login_url {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php:31, Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:138)"} []
[2017-03-10 16:13:14] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Notice: Undefined index: server_login_url" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php line 31 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php:31, Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:138)"} []
[2017-03-10 16:13:14] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php line 31) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php:31)"} []
[2017-03-10 16:13:19] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /flush"" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/dev/classes.php line 3485 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /flush\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/dev/classes.php:3485, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:138)"} []
[2017-03-10 16:13:19] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php line 31) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php:31)"} []
[2017-03-10 16:13:19] php.CRITICAL: Uncaught Notice: Undefined index: server_login_url {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php:31, Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /flush\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/dev/classes.php:3485, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:138)"} []
[2017-03-10 16:13:19] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Notice: Undefined index: server_login_url" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php line 31 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php:31, Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /flush\" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/dev/classes.php:3485, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/var/cache/dev/appDevDebugProjectContainerUrlMatcher.php:138)"} []
[2017-03-10 16:13:19] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php line 31) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php:31)"} []
[2017-03-10 16:13:29] request.INFO: Matched route "flush". {"route":"flush","route_parameters":{"_controller":"AppBundle\\Controller\\MainController::flushAction","_route":"flush"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/flush","method":"GET"} []
[2017-03-10 16:13:29] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Notice: Undefined index: server_login_url" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php line 31 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php:31)"} []
[2017-03-10 16:13:29] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php line 31) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php:31)"} []
[2017-03-10 16:13:29] php.CRITICAL: Uncaught Notice: Undefined index: server_login_url {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php:31, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php:31)"} []
[2017-03-10 16:13:29] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Notice: Undefined index: server_login_url" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php line 31 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php:31, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php:31)"} []
[2017-03-10 16:13:29] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php line 31) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php:31)"} []
[2017-03-10 16:13:31] request.INFO: Matched route "flush". {"route":"flush","route_parameters":{"_controller":"AppBundle\\Controller\\MainController::flushAction","_route":"flush"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/flush","method":"GET"} []
[2017-03-10 16:13:31] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Notice: Undefined index: server_login_url" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php line 31 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php:31)"} []
[2017-03-10 16:13:31] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php line 31) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php:31)"} []
[2017-03-10 16:13:31] php.CRITICAL: Uncaught Notice: Undefined index: server_login_url {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php:31, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php:31)"} []
[2017-03-10 16:13:31] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Notice: Undefined index: server_login_url" at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php line 31 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php:31, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php:31)"} []
[2017-03-10 16:13:31] request.CRITICAL: Exception thrown when handling an exception (Symfony\Component\Debug\Exception\ContextErrorException: Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php line 31) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined index: server_login_url at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/prayno/casauth-bundle/PRayno/CasAuthBundle/Security/CasAuthenticator.php:31)"} []
[2017-03-10 16:14:18] request.INFO: Matched route "flush". {"route":"flush","route_parameters":{"_controller":"AppBundle\\Controller\\MainController::flushAction","_route":"flush"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/flush","method":"GET"} []
[2017-03-10 16:14:18] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-10 16:14:18] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:14:18] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:14:18] security.INFO: Guard authentication successful! {"token":"[object] (Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken: PostAuthenticationGuardToken(user=\"test\", authenticated=true, roles=\"ROLE_USER\"))","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:14:18] security.DEBUG: Guard authenticator set no success response: request continues. {"authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:14:18] security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:14:19] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-10 16:14:35] request.INFO: Matched route "api_service". {"route":"api_service","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::serviceAction","uid":"i","_route":"api_service"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/api/service/call/i","method":"GET"} []
[2017-03-10 16:14:35] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-10 16:14:35] security.DEBUG: User was reloaded from a user provider. {"username":"test","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-10 16:14:35] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-10 16:14:35] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:14:35] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:14:35] security.INFO: Guard authentication successful! {"token":"[object] (Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken: PostAuthenticationGuardToken(user=\"test\", authenticated=true, roles=\"ROLE_USER\"))","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:14:35] security.DEBUG: Guard authenticator set no success response: request continues. {"authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:14:35] security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:14:35] doctrine.DEBUG: SELECT t0.id AS id_1, t0.uid AS uid_2 FROM user_app t0 WHERE t0.uid = ? LIMIT 1 ["test"] []
[2017-03-10 16:14:35] doctrine.DEBUG: SELECT t0.id AS id_1, t0.uid AS uid_2, t0.name AS name_3, t0.url AS url_4, t0.description AS description_5 FROM service t0 WHERE t0.uid = ? LIMIT 1 ["i"] []
[2017-03-10 16:14:35] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.uid AS uid_2, t0.name AS name_3, t0.url AS url_4, t0.description AS description_5 FROM service t0 WHERE t0.uid = ? LIMIT 1' with params ["i"]:  SQLSTATE[42703]: Undefined column: 7 ERREUR:  la colonne t0.uid n'existe pas LINE 1: SELECT t0.id AS id_1, t0.uid AS uid_2, t0.name AS name_3, t0...                               ^ HINT:  Peut-Ãªtre que vous souhaitiez rÃ©fÃ©rencer la colonne Â« t0.id Â»." at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php line 72 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.uid AS uid_2, t0.name AS name_3, t0.url AS url_4, t0.description AS description_5 FROM service t0 WHERE t0.uid = ? LIMIT 1' with params [\"i\"]:\n\nSQLSTATE[42703]: Undefined column: 7 ERREUR:  la colonne t0.uid n'existe pas\nLINE 1: SELECT t0.id AS id_1, t0.uid AS uid_2, t0.name AS name_3, t0...\n                              ^\nHINT:  Peut-Ãªtre que vous souhaitiez rÃ©fÃ©rencer la colonne Â« t0.id Â». at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:72, Doctrine\\DBAL\\Driver\\PDOException(code: 42703): SQLSTATE[42703]: Undefined column: 7 ERREUR:  la colonne t0.uid n'existe pas\nLINE 1: SELECT t0.id AS id_1, t0.uid AS uid_2, t0.name AS name_3, t0...\n                              ^\nHINT:  Peut-Ãªtre que vous souhaitiez rÃ©fÃ©rencer la colonne Â« t0.id Â». at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42703): SQLSTATE[42703]: Undefined column: 7 ERREUR:  la colonne t0.uid n'existe pas\nLINE 1: SELECT t0.id AS id_1, t0.uid AS uid_2, t0.name AS name_3, t0...\n                              ^\nHINT:  Peut-Ãªtre que vous souhaitiez rÃ©fÃ©rencer la colonne Â« t0.id Â». at /mnt/traban_home/6ir1/vrasquie/WWW-perso/cas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2017-03-10 16:14:36] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-10 16:14:37] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"854b59","_route":"_wdt"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/_wdt/854b59","method":"GET"} []
[2017-03-10 16:16:09] request.INFO: Matched route "api_service". {"route":"api_service","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::serviceAction","uid":"i","_route":"api_service"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/api/service/call/i","method":"GET"} []
[2017-03-10 16:16:09] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-10 16:16:09] security.DEBUG: User was reloaded from a user provider. {"username":"test","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-10 16:16:09] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-10 16:16:09] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:16:09] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:16:09] security.INFO: Guard authentication successful! {"token":"[object] (Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken: PostAuthenticationGuardToken(user=\"test\", authenticated=true, roles=\"ROLE_USER\"))","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:16:09] security.DEBUG: Guard authenticator set no success response: request continues. {"authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:16:09] security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:16:09] doctrine.DEBUG: SELECT t0.id AS id_1, t0.uid AS uid_2 FROM user_app t0 WHERE t0.uid = ? LIMIT 1 ["test"] []
[2017-03-10 16:16:09] doctrine.DEBUG: SELECT t0.id AS id_1, t0.uid AS uid_2, t0.name AS name_3, t0.url AS url_4, t0.description AS description_5 FROM service t0 WHERE t0.uid = ? LIMIT 1 ["i"] []
[2017-03-10 16:16:10] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-10 16:17:54] request.INFO: Matched route "api_service". {"route":"api_service","route_parameters":{"_controller":"AppBundle\\Controller\\ApiController::serviceAction","uid":"acf2feb0-05a4-11e7-93ae-92361f002671","_route":"api_service"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/api/service/call/acf2feb0-05a4-11e7-93ae-92361f002671","method":"GET"} []
[2017-03-10 16:17:54] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-10 16:17:54] security.DEBUG: User was reloaded from a user provider. {"username":"test","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-10 16:17:54] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-10 16:17:54] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:17:54] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:17:54] security.INFO: Guard authentication successful! {"token":"[object] (Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken: PostAuthenticationGuardToken(user=\"test\", authenticated=true, roles=\"ROLE_USER\"))","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:17:54] security.DEBUG: Guard authenticator set no success response: request continues. {"authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:17:54] security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:17:54] doctrine.DEBUG: SELECT t0.id AS id_1, t0.uid AS uid_2 FROM user_app t0 WHERE t0.uid = ? LIMIT 1 ["test"] []
[2017-03-10 16:17:54] doctrine.DEBUG: SELECT t0.id AS id_1, t0.uid AS uid_2, t0.name AS name_3, t0.url AS url_4, t0.description AS description_5 FROM service t0 WHERE t0.uid = ? LIMIT 1 ["acf2feb0-05a4-11e7-93ae-92 [...]"] []
[2017-03-10 16:17:54] doctrine.DEBUG: SELECT s0_.id AS id_0, s0_.uid AS uid_1, s0_.name AS name_2, s0_.url AS url_3, s0_.description AS description_4 FROM service s0_ INNER JOIN users_services u2_ ON s0_.id = u2_.service_id INNER JOIN user_app u1_ ON u1_.id = u2_.user_id WHERE u1_.uid = ? LIMIT 1 [1] []
[2017-03-10 16:17:55] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-10 16:18:53] request.INFO: Matched route "flush". {"route":"flush","route_parameters":{"_controller":"AppBundle\\Controller\\MainController::flushAction","_route":"flush"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/flush","method":"GET"} []
[2017-03-10 16:18:53] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-10 16:18:53] security.DEBUG: User was reloaded from a user provider. {"username":"test","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-10 16:18:53] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-10 16:18:53] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:18:53] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:18:53] security.INFO: Guard authentication successful! {"token":"[object] (Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken: PostAuthenticationGuardToken(user=\"test\", authenticated=true, roles=\"ROLE_USER\"))","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:18:53] security.DEBUG: Guard authenticator set no success response: request continues. {"authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:18:53] security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-10 16:18:54] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-13 10:25:45] request.INFO: Matched route "flush". {"route":"flush","route_parameters":{"_controller":"AppBundle\\Controller\\MainController::flushAction","_route":"flush"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/flush","method":"GET"} []
[2017-03-13 10:25:45] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-13 10:25:45] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-13 10:25:45] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-13 10:25:45] security.INFO: Guard authentication successful! {"token":"[object] (Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken: PostAuthenticationGuardToken(user=\"test\", authenticated=true, roles=\"ROLE_USER\"))","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-13 10:25:45] security.DEBUG: Guard authenticator set no success response: request continues. {"authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-13 10:25:45] security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-13 10:25:46] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-13 10:28:46] request.INFO: Matched route "flush". {"route":"flush","route_parameters":{"_controller":"AppBundle\\Controller\\MainController::flushAction","_route":"flush"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/flush","method":"GET"} []
[2017-03-13 10:28:46] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-13 10:28:46] security.DEBUG: User was reloaded from a user provider. {"username":"test","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-13 10:28:46] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-13 10:28:46] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-13 10:28:46] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-13 10:28:46] security.INFO: Guard authentication successful! {"token":"[object] (Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken: PostAuthenticationGuardToken(user=\"test\", authenticated=true, roles=\"ROLE_USER\"))","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-13 10:28:46] security.DEBUG: Guard authenticator set no success response: request continues. {"authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-13 10:28:46] security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-13 10:28:46] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-13 10:35:36] request.INFO: Matched route "flush". {"route":"flush","route_parameters":{"_controller":"AppBundle\\Controller\\MainController::flushAction","_route":"flush"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/flush","method":"GET"} []
[2017-03-13 10:35:36] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-03-13 10:35:36] security.DEBUG: User was reloaded from a user provider. {"username":"test","provider":"PRayno\\CasAuthBundle\\Security\\User\\CasUserProvider"} []
[2017-03-13 10:35:36] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-13 10:35:36] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-13 10:35:36] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-13 10:35:36] security.INFO: Guard authentication successful! {"token":"[object] (Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken: PostAuthenticationGuardToken(user=\"test\", authenticated=true, roles=\"ROLE_USER\"))","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-13 10:35:36] security.DEBUG: Guard authenticator set no success response: request continues. {"authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-13 10:35:36] security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-13 10:35:37] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-15 11:11:06] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_controller":"AppBundle\\Controller\\MainController::indexAction","_route":"home"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/~vrasquie/cas/","method":"GET"} []
[2017-03-15 11:11:06] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2017-03-15 11:11:06] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-15 11:11:06] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"main","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-15 11:11:06] security.INFO: Guard authentication successful! {"token":"[object] (Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken: PostAuthenticationGuardToken(user=\"test\", authenticated=true, roles=\"ROLE_USER\"))","authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-15 11:11:06] security.DEBUG: Guard authenticator set no success response: request continues. {"authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-15 11:11:06] security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"AppBundle\\Security\\CasEnablerAuthenticator"} []
[2017-03-15 11:11:06] doctrine.DEBUG: SELECT t0.id AS id_1, t0.uid AS uid_2, t0.name AS name_3, t0.url AS url_4, t0.description AS description_5 FROM service t0 [] []
[2017-03-15 11:11:07] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-03-15 11:11:08] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"386f87","_route":"_wdt"},"request_uri":"https://perso-etudiant.u-pem.fr/~vrasquie/cas/web/app_dev.php/_wdt/386f87","method":"GET"} []
